version: "3.5"

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mybb
      MYSQL_USER: mybb
      MYSQL_PASSWORD: root
    networks:
      - database-network
    restart: on-failure
    volumes:
     - ~/Database/db/mariadb:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - database-network

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgrespass}
      PGDATA: /data/postgres
    volumes:
      - ~/Database/db/pg/:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - database-network
    restart: unless-stopped
    
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-adminpass}
    volumes:
      - ~/Database/db/pgadmin/:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - database-network
    restart: unless-stopped
  
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpress
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoexpresspass
    links:
      - mongo
    networks:
      - database-network

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongopass
    ports:
      - "27017:27017"
    volumes:
      - ~/Database/db/mongo/:/data/db
    networks:
      - database-network
        
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass redispass
    ports:
     - "6379:6379"
    volumes:
     - ~/Database/db/redis-data:/var/lib/redis
      - ~/Database/db/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - database-network
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=redispass
    ports:
      - 8082:8082
    depends_on:
      - redis
    networks:
      - database-network
  oracle-db:
    image: oracleinanutshell/oracle-xe-11g:latest
    ports:
      - 1521:1521
      - 5500:5500
    environment:
      - "DB_CONNSTR=db.box:1521/orcl"
      - "DB_TSAM_USER=oracle"
      - "DB_TSAM_PASSWD=oraclepass"
      - "TSAM_CONSOLE_ADMIN_PASSWD=oraclepass"
      - "DBA_USER=sys"
      - "DBA_PASSWD=oraclepass"
      - "DB_TSAM_TBLSPACE=users"
      - "WLS_PW=oraclepass"
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "sqlserverpass"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
      
networks:
  database-network:
    driver: bridge
